"""added image

Revision ID: 16c3ab9fd3e2
Revises: 07b35113ea4c
Create Date: 2021-09-21 19:36:59.251694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c3ab9fd3e2'
down_revision = '07b35113ea4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image')
    # ### end Alembic commands ###
